const readlineSync = require("readline-sync");
const firstHomeworkGrade = readlineSync.question("\nEnter three homework grades.\n");
const secondHomeworkGrade = readlineSync.question("");
const thirdHomeworkGrade = readlineSync.question("");
const averageHomeworkGrade = (parseFloat(firstHomeworkGrade)+parseFloat(secondHomeworkGrade)+parseFloat(thirdHomeworkGrade))/3*.15;
const firstQuizGrade = readlineSync.question("\nEnter three quiz grades.\n");
const secondQuizGrade = readlineSync.question("");
const thirdQuizGrade = readlineSync.question("");
const averageQuizGrade = (parseFloat(firstQuizGrade)+parseFloat(secondQuizGrade)+parseFloat(thirdQuizGrade))/3*.35;
const firstTestGrade = readlineSync.question("\nEnter three test grades.\n");
const secondTestGrade = readlineSync.question("");
const thirdTestGrade = readlineSync.question("");
const averageTestGrade = (parseFloat(firstTestGrade)+parseFloat(secondTestGrade)+parseFloat(thirdTestGrade))/3*.5;
let finalGrade = (parseFloat(averageHomeworkGrade)+parseFloat(averageQuizGrade)+parseFloat(averageTestGrade));
finalGrade = finalGrade.toLocaleString("en", { minimumFractionDigits: 2, maximumFractionDigits: 2});
console.log("\nYour marking period grade is " + finalGrade + "%.\n");
