const readlineSync=require("readline-sync");
let salary = readlineSync.question("\nAnnual salary: ");
salary = salary/24;
const pretax = (salary*.93);
const fed =pretax*.157;
const inc = pretax*.0447;
const soc = pretax*.062;
const med = pretax*.0145;
let total = pretax-(fed+inc+soc+med);
total = total.toLocaleString("en", { minimumFractionDigits: 2, maximumFractionDigits: 2});
console.log("\nYour take-home pay each check will be $"+ total+".\n");
